
# This file is automatically generated, you probably don't want to edit this

contabOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contabOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            correction = "ob",
            obs = TRUE,
            exp = FALSE,
            sr = FALSE,
            ss = FALSE,
            pcRow = FALSE,
            pcCol = FALSE,
            pcTot = FALSE,
            varA = FALSE,
            text = TRUE,
            barplot = FALSE,
            yaxis = "ycounts",
            yaxisPc = "total_pc",
            xaxis = "xrows",
            bartype = "dodge", ...) {

            super$initialize(
                package="jeva",
                name="contab",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "nc",
                    "ob",
                    "aic"),
                default="ob")
            private$..obs <- jmvcore::OptionBool$new(
                "obs",
                obs,
                default=TRUE)
            private$..exp <- jmvcore::OptionBool$new(
                "exp",
                exp,
                default=FALSE)
            private$..sr <- jmvcore::OptionBool$new(
                "sr",
                sr,
                default=FALSE)
            private$..ss <- jmvcore::OptionBool$new(
                "ss",
                ss,
                default=FALSE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
            private$..pcTot <- jmvcore::OptionBool$new(
                "pcTot",
                pcTot,
                default=FALSE)
            private$..varA <- jmvcore::OptionBool$new(
                "varA",
                varA,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)
            private$..barplot <- jmvcore::OptionBool$new(
                "barplot",
                barplot,
                default=FALSE)
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "ycounts",
                    "ypc"),
                default="ycounts")
            private$..yaxisPc <- jmvcore::OptionList$new(
                "yaxisPc",
                yaxisPc,
                options=list(
                    "total_pc",
                    "column_pc",
                    "row_pc"),
                default="total_pc")
            private$..xaxis <- jmvcore::OptionList$new(
                "xaxis",
                xaxis,
                options=list(
                    "xrows",
                    "xcols"),
                default="xrows")
            private$..bartype <- jmvcore::OptionList$new(
                "bartype",
                bartype,
                options=list(
                    "dodge",
                    "stack"),
                default="dodge")

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..correction)
            self$.addOption(private$..obs)
            self$.addOption(private$..exp)
            self$.addOption(private$..sr)
            self$.addOption(private$..ss)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..pcTot)
            self$.addOption(private$..varA)
            self$.addOption(private$..text)
            self$.addOption(private$..barplot)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..yaxisPc)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..bartype)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        correction = function() private$..correction$value,
        obs = function() private$..obs$value,
        exp = function() private$..exp$value,
        sr = function() private$..sr$value,
        ss = function() private$..ss$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value,
        pcTot = function() private$..pcTot$value,
        varA = function() private$..varA$value,
        text = function() private$..text$value,
        barplot = function() private$..barplot$value,
        yaxis = function() private$..yaxis$value,
        yaxisPc = function() private$..yaxisPc$value,
        xaxis = function() private$..xaxis$value,
        bartype = function() private$..bartype$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..correction = NA,
        ..obs = NA,
        ..exp = NA,
        ..sr = NA,
        ..ss = NA,
        ..pcRow = NA,
        ..pcCol = NA,
        ..pcTot = NA,
        ..varA = NA,
        ..text = NA,
        ..barplot = NA,
        ..yaxis = NA,
        ..yaxisPc = NA,
        ..xaxis = NA,
        ..bartype = NA)
)

contabResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contabResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        text = function() private$.items[["text"]],
        cttma = function() private$.items[["cttma"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]],
        ctt3 = function() private$.items[["ctt3"]],
        barplot = function() private$.items[["barplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Independent Samples")
            self$add(jmvcore::Table$new(
                options=options,
                name="freqs",
                title="Contingency Table",
                columns=list(),
                clearWith=list(
                    "data",
                    "rows",
                    "cols",
                    "counts",
                    "exp",
                    "obs",
                    "sr",
                    "ss",
                    "pcRow",
                    "pcCol",
                    "pcTot")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="cttma",
                title="main results",
                rows=4,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "correction"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `title`="Expected value", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="number"),
                    list(
                        `name`="G", 
                        `title`="G", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "EdwardsCT",
                            "Edwards_OR",
                            "Glover_Tut")))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                clearWith=list(
                    "varA",
                    "data",
                    "counts",
                    "rows",
                    "cols",
                    "correction"),
                visible="(text)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="LR", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt3",
                title="Variance analysis versus Null model",
                visible="(varA)",
                rows=3,
                clearWith=list(
                    "counts",
                    "rows",
                    "cols"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Sv", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="X2", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="dfv", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pv", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pv1", 
                        `title`="1 - p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "EdwardsVA")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="barplot",
                title="Plots",
                width=450,
                height=400,
                renderFun=".barPlot",
                visible="(barplot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "barplot",
                    "yaxis",
                    "yaxisPc",
                    "xaxis",
                    "bartype",
                    "pcTot",
                    "pcCol",
                    "pcRow")))}))

contabBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contabBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "contab",
                version = c(1,0,0),
                options = options,
                results = contabResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' Independent Samples
#'
#' Two-way analysis of a contingency table where main effects and interaction 
#' can be assessed.
#' 
#'
#' @examples
#' dat <- data.frame(
#'   Infested = c('Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No'),
#'   Age = c(1,2,3,4,5),
#'   Eggs = c(14, 16, 14, 7, 6, 87, 33, 66, 34, 11),
#'   check.names=FALSE)
#'
#' jeva::contab(formula = Eggs ~ Infested:Age, data = dat, text = FALSE)
#'
#' @param data the data as a data frame
#' @param rows the variable to use as the rows in the contingency table
#' @param cols the variable to use as the columns in the contingency table
#' @param counts the variable for counts, required
#' @param correction correction for parameters, none, Occam's bonus (default)
#'   or AIC
#' @param obs \code{TRUE} or \code{FALSE} (default), provide the observed
#'   counts
#' @param exp \code{TRUE} or \code{FALSE} (default), provide the expected
#'   counts
#' @param sr \code{TRUE} or \code{FALSE} (default), provide the standardized
#'   residuals
#' @param ss \code{TRUE} or \code{FALSE} (default), provide the signed S
#'   values
#' @param pcRow \code{TRUE} or \code{FALSE} (default), provide row percentages
#' @param pcCol \code{TRUE} or \code{FALSE} (default), provide column
#'   percentages
#' @param pcTot \code{TRUE} or \code{FALSE} (default), provide total
#'   percentages
#' @param varA \code{TRUE} or \code{FALSE} (default), perform variance
#'   analysis against the null model
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @param barplot \code{TRUE} or \code{FALSE} (default), show barplots
#' @param yaxis ycounts (default) or ypc. Use respectively \code{counts} or
#'   \code{percentages} for the bar plot y-axis
#' @param yaxisPc total_pc (default), column_pc, or row_pc. Use respectively
#'   percentages \code{of total}, \code{within columns}, or \code{within rows}
#'   for the bar plot y-axis.
#' @param xaxis rows (default), or columns in bar plot X axis
#' @param bartype stack or side by side (default), barplot type
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a proportions table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cttma} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ctt3} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$barplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqs$asDF}
#'
#' \code{as.data.frame(results$freqs)}
#'
#' @export
contab <- function(
    data,
    rows,
    cols,
    counts = NULL,
    correction = "ob",
    obs = TRUE,
    exp = FALSE,
    sr = FALSE,
    ss = FALSE,
    pcRow = FALSE,
    pcCol = FALSE,
    pcTot = FALSE,
    varA = FALSE,
    text = TRUE,
    barplot = FALSE,
    yaxis = "ycounts",
    yaxisPc = "total_pc",
    xaxis = "xrows",
    bartype = "dodge",
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("contab requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(counts))
            counts <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                type="vars",
                subset="1")
        if (missing(rows))
            rows <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="1")
        if (missing(cols))
            cols <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="2")
        if (missing(layers))
            layers <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="3:")
    }

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- contabOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        correction = correction,
        obs = obs,
        exp = exp,
        sr = sr,
        ss = ss,
        pcRow = pcRow,
        pcCol = pcCol,
        pcTot = pcTot,
        varA = varA,
        text = text,
        barplot = barplot,
        yaxis = yaxis,
        yaxisPc = yaxisPc,
        xaxis = xaxis,
        bartype = bartype)

    analysis <- contabClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

