
# This file is automatically generated, you probably don't want to edit this

cttOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cttOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            nul = 1,
            alt = 1,
            lint = 2,
            ciWidth = 95,
            correction = "ob",
            pll = FALSE,
            plotype = "lplot",
            supplot = -10,
            varA = FALSE,
            cc = FALSE,
            text = TRUE,
            obs = TRUE,
            exp = FALSE,
            pcRow = FALSE,
            pcCol = FALSE,
            pcTot = FALSE,
            barplot = FALSE,
            yaxis = "ycounts",
            yaxisPc = "total_pc",
            xaxis = "xrows",
            bartype = "dodge", ...) {

            super$initialize(
                package="jeva",
                name="ctt",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..nul <- jmvcore::OptionNumber$new(
                "nul",
                nul,
                min=0,
                max=100000000000,
                default=1)
            private$..alt <- jmvcore::OptionNumber$new(
                "alt",
                alt,
                min=0,
                max=100000000000,
                default=1)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "nc",
                    "ob",
                    "aic"),
                default="ob")
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)
            private$..plotype <- jmvcore::OptionList$new(
                "plotype",
                plotype,
                options=list(
                    "lplot",
                    "logplot"),
                default="lplot")
            private$..supplot <- jmvcore::OptionNumber$new(
                "supplot",
                supplot,
                min=-100,
                max=-1,
                default=-10)
            private$..varA <- jmvcore::OptionBool$new(
                "varA",
                varA,
                default=FALSE)
            private$..cc <- jmvcore::OptionBool$new(
                "cc",
                cc,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)
            private$..obs <- jmvcore::OptionBool$new(
                "obs",
                obs,
                default=TRUE)
            private$..exp <- jmvcore::OptionBool$new(
                "exp",
                exp,
                default=FALSE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
            private$..pcTot <- jmvcore::OptionBool$new(
                "pcTot",
                pcTot,
                default=FALSE)
            private$..barplot <- jmvcore::OptionBool$new(
                "barplot",
                barplot,
                default=FALSE)
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "ycounts",
                    "ypc"),
                default="ycounts")
            private$..yaxisPc <- jmvcore::OptionList$new(
                "yaxisPc",
                yaxisPc,
                options=list(
                    "total_pc",
                    "column_pc",
                    "row_pc"),
                default="total_pc")
            private$..xaxis <- jmvcore::OptionList$new(
                "xaxis",
                xaxis,
                options=list(
                    "xrows",
                    "xcols"),
                default="xrows")
            private$..bartype <- jmvcore::OptionList$new(
                "bartype",
                bartype,
                options=list(
                    "dodge",
                    "stack"),
                default="dodge")

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..nul)
            self$.addOption(private$..alt)
            self$.addOption(private$..lint)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..correction)
            self$.addOption(private$..pll)
            self$.addOption(private$..plotype)
            self$.addOption(private$..supplot)
            self$.addOption(private$..varA)
            self$.addOption(private$..cc)
            self$.addOption(private$..text)
            self$.addOption(private$..obs)
            self$.addOption(private$..exp)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..pcTot)
            self$.addOption(private$..barplot)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..yaxisPc)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..bartype)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        nul = function() private$..nul$value,
        alt = function() private$..alt$value,
        lint = function() private$..lint$value,
        ciWidth = function() private$..ciWidth$value,
        correction = function() private$..correction$value,
        pll = function() private$..pll$value,
        plotype = function() private$..plotype$value,
        supplot = function() private$..supplot$value,
        varA = function() private$..varA$value,
        cc = function() private$..cc$value,
        text = function() private$..text$value,
        obs = function() private$..obs$value,
        exp = function() private$..exp$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value,
        pcTot = function() private$..pcTot$value,
        barplot = function() private$..barplot$value,
        yaxis = function() private$..yaxis$value,
        yaxisPc = function() private$..yaxisPc$value,
        xaxis = function() private$..xaxis$value,
        bartype = function() private$..bartype$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..nul = NA,
        ..alt = NA,
        ..lint = NA,
        ..ciWidth = NA,
        ..correction = NA,
        ..pll = NA,
        ..plotype = NA,
        ..supplot = NA,
        ..varA = NA,
        ..cc = NA,
        ..text = NA,
        ..obs = NA,
        ..exp = NA,
        ..pcRow = NA,
        ..pcCol = NA,
        ..pcTot = NA,
        ..barplot = NA,
        ..yaxis = NA,
        ..yaxisPc = NA,
        ..xaxis = NA,
        ..bartype = NA)
)

cttResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cttResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        text = function() private$.items[["text"]],
        ctt = function() private$.items[["ctt"]],
        cttma = function() private$.items[["cttma"]],
        ctt2 = function() private$.items[["ctt2"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]],
        ctt3 = function() private$.items[["ctt3"]],
        plotc = function() private$.items[["plotc"]],
        barplot = function() private$.items[["barplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Odds Ratio")
            self$add(jmvcore::Table$new(
                options=options,
                name="freqs",
                title="Contingency Table",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt",
                title="Odds Ratio analyses",
                rows=3,
                refs=list(
                    "Glover_Tut",
                    "Edwards_OR"),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "nul",
                    "alt",
                    "correction"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `title`="OR Value", 
                        `type`="number"),
                    list(
                        `name`="ordiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="number"),
                    list(
                        `name`="G", 
                        `title`="G", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cttma",
                title="Marginal main effects and interaction analyses",
                rows=4,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "correction"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `title`="Expected value", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="number"),
                    list(
                        `name`="G", 
                        `title`="G", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "Glover_Tut",
                            "Edwards_OR",
                            "EdwardsCT")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt2",
                title="Intervals for OR",
                rows=2,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "lint",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="Interval", 
                        `title`="Type of interval", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `type`="text"),
                    list(
                        `name`="OR", 
                        `title`="OR", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number", 
                        `refs`=list(
                            "Pritikin")))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                visible="(text)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "correction",
                    "lint")))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="LR", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt3",
                title="Variance analysis",
                visible="(varA)",
                rows="1 - rows - cols - counts - data - cc",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Sv", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="X2", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="dfv", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="pv", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pv1", 
                        `title`="1 - p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "EdwardsVA")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood curve for OR with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "lint",
                    "nul",
                    "alt",
                    "plotype",
                    "supplot"),
                visible="(pll)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="barplot",
                title="Plots",
                width=450,
                height=400,
                renderFun=".barPlot",
                visible="(barplot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "barplot",
                    "yaxis",
                    "yaxisPc",
                    "xaxis",
                    "bartype",
                    "pcTot",
                    "pcCol",
                    "pcRow")))}))

cttBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cttBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "ctt",
                version = c(1,0,0),
                options = options,
                results = cttResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Odds Ratio
#'
#' Analysis of a 2 x 2 contingency table using the odds ratio, choose null and 
#' alternative values
#' 
#'
#' @examples
#' dat <- data.frame(
#'   Treatment = c('Folic acid', 'Folic acid', 'Placebo', 'Placebo'),
#'   Defect = c('Yes', 'No','Yes', 'No'),
#'   count = c(6, 587, 21, 581),
#'   check.names=FALSE)
#'
#'  jeva::ctt(formula = count ~ Treatment:Defect, data = dat, text=FALSE)
#'   #
#'   # ODDS RATIO
#'   #
#'   # Contingency Tables
#'   # --------------------------------------
#'   #   Treatment     No      Yes    Total
#'   # --------------------------------------
#'   #   Folic acid     587      6      593
#'   #   Placebo        581     21      602
#'   #   Total         1168     27     1195
#'   # --------------------------------------
#'   #
#'   #
#'   # Support: Odds Ratio analyses
#'   # ----------------------------------------------------------------------------------------------------
#'   #                       OR Value    Difference    S             Param    G           df    p
#'   # ----------------------------------------------------------------------------------------------------
#'   #   H₀ vs odds ratio    1.000000     -2.536145    -3.8944209     1, 2    8.788842     1    0.0030308
#'   #   Ha vs odds ratio    1.000000     -2.536145    -4.3944209     2, 2    8.788842     1    0.0030308
#'   #   Ha vs H₀                          0.000000    -0.5000000     2, 1    0.000000     1    1.0000000
#'   # ----------------------------------------------------------------------------------------------------
#'   #   Note. S uses Occam's Bonus correction for parameters (Param).
#'   #
#'   #
#'   # Support: Marginal main effects and interaction analyses, against the Null model
#'   # -------------------------------------------------------------------------------------------------------
#'   #   Component               Expected value    S              Param    G                df    p
#'   # -------------------------------------------------------------------------------------------------------
#'   #   Treatment                     597.5000     -0.4661085     2, 1       0.06778307     1     0.7945924
#'   #   Defect                        597.5000    698.7864811     2, 1    1398.57296214     1    < .0000001
#'   #   Treatment  ⨯  Defect                        3.8944260     2, 1       8.78885199     1     0.0030308
#'   #   Total                         298.7500    702.2147986     4, 1    1407.42959720     3    < .0000001
#'   # -------------------------------------------------------------------------------------------------------
#'   #   Note. S uses Occam's Bonus correction for parameters (Param).  The interaction and OR (against 1)
#'   #   will have the same S value. Adding the S values for the 3 components will precisely sum to the
#'   #   total S when no parameter correction is applied.
#'   #
#'   #
#'   # Intervals for OR
#'   # -------------------------------------------------------------------
#'   #   Type of interval      Level    OR          Lower       Upper
#'   # -------------------------------------------------------------------
#'   #   Support               2        3.536145    1.479229    9.915968
#'   #   Likelihood-based a    95\%      3.536145    1.503876    9.690701
#'   # -------------------------------------------------------------------
#'   #   a See reference Pritikin et al (2017) such intervals are more
#'   #   accurate and are parameterization-invariant compared to
#'   #   conventional confidence intervals
#'   #
#'
#' @param data the data as a data frame
#' @param rows the variable to use as the rows in the contingency table (not
#'   necessary when providing a formula, see the examples)
#' @param cols the variable to use as the columns in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param counts the variable to use as the counts in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param nul value for the null hypothesis, default = 1
#' @param alt value for the alternative hypothesis, default = 1
#' @param lint likelihood interval given as support value, e.g. 2 or 3,
#'   default = 2
#' @param ciWidth a number between 50 and 99.9 (default: 95), width of the
#'   confidence intervals to provide
#' @param correction correction for parameters, none, Occam's bonus (default)
#'   or AIC
#' @param pll \code{TRUE} or \code{FALSE} (default), give the likelihood
#'   function showing null hypothesis (black line),  alternative hypothesis
#'   (blue line), mean (dashed line), and specified support interval
#'   (horizontal red line)
#' @param plotype choose type of plot, likelihood function (default), support
#'   function
#' @param supplot To set the minimum likelihood display value in plot, in log
#'   units (default = -10)  affects the x-axis range
#' @param varA \code{TRUE} or \code{FALSE} (default), perform variance
#'   analysis for null and alternative hypothesis
#' @param cc \code{TRUE} or \code{FALSE} (default), use continuity correction
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @param obs \code{TRUE} or \code{FALSE} (default), provide the observed
#'   counts
#' @param exp \code{TRUE} or \code{FALSE} (default), provide the expected
#'   counts
#' @param pcRow \code{TRUE} or \code{FALSE} (default), provide row percentages
#' @param pcCol \code{TRUE} or \code{FALSE} (default), provide column
#'   percentages
#' @param pcTot \code{TRUE} or \code{FALSE} (default), provide total
#'   percentages
#' @param barplot \code{TRUE} or \code{FALSE} (default), show barplots
#' @param yaxis ycounts (default) or ypc. Use respectively \code{counts} or
#'   \code{percentages} for the bar plot y-axis
#' @param yaxisPc total_pc (default), column_pc, or row_pc. Use respectively
#'   percentages \code{of total}, \code{within columns}, or \code{within rows}
#'   for the bar plot y-axis.
#' @param xaxis rows (default), or columns in bar plot X axis
#' @param bartype stack or side by side (default), barplot type
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ctt} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cttma} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ctt2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ctt3} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$barplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqs$asDF}
#'
#' \code{as.data.frame(results$freqs)}
#'
#' @export
ctt <- function(
    data,
    rows,
    cols,
    counts = NULL,
    nul = 1,
    alt = 1,
    lint = 2,
    ciWidth = 95,
    correction = "ob",
    pll = FALSE,
    plotype = "lplot",
    supplot = -10,
    varA = FALSE,
    cc = FALSE,
    text = TRUE,
    obs = TRUE,
    exp = FALSE,
    pcRow = FALSE,
    pcCol = FALSE,
    pcTot = FALSE,
    barplot = FALSE,
    yaxis = "ycounts",
    yaxisPc = "total_pc",
    xaxis = "xrows",
    bartype = "dodge",
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ctt requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(counts))
            counts <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                type="vars",
                subset="1")
        if (missing(rows))
            rows <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="1")
        if (missing(cols))
            cols <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="2")
    }

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- cttOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        nul = nul,
        alt = alt,
        lint = lint,
        ciWidth = ciWidth,
        correction = correction,
        pll = pll,
        plotype = plotype,
        supplot = supplot,
        varA = varA,
        cc = cc,
        text = text,
        obs = obs,
        exp = exp,
        pcRow = pcRow,
        pcCol = pcCol,
        pcTot = pcTot,
        barplot = barplot,
        yaxis = yaxis,
        yaxisPc = yaxisPc,
        xaxis = xaxis,
        bartype = bartype)

    analysis <- cttClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

