
# This file is automatically generated, you probably don't want to edit this

laov1wOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "laov1wOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            group = NULL,
            ct1 = FALSE,
            Ct1Values = "1,-1,...",
            ct2 = FALSE,
            Ct2Values = "1,-1,...",
            lint = 2,
            desc = FALSE,
            descPlot = FALSE,
            text = TRUE,
            norm = FALSE,
            qq = FALSE,
            eqv = FALSE, ...) {

            super$initialize(
                package="jeva",
                name="laov1w",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariable$new(
                "deps",
                deps,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                required=TRUE,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..ct1 <- jmvcore::OptionBool$new(
                "ct1",
                ct1,
                default=FALSE)
            private$..Ct1Values <- jmvcore::OptionString$new(
                "Ct1Values",
                Ct1Values,
                default="1,-1,...")
            private$..ct2 <- jmvcore::OptionBool$new(
                "ct2",
                ct2,
                default=FALSE)
            private$..Ct2Values <- jmvcore::OptionString$new(
                "Ct2Values",
                Ct2Values,
                default="1,-1,...")
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=10,
                default=2)
            private$..desc <- jmvcore::OptionBool$new(
                "desc",
                desc,
                default=FALSE)
            private$..descPlot <- jmvcore::OptionBool$new(
                "descPlot",
                descPlot,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)
            private$..norm <- jmvcore::OptionBool$new(
                "norm",
                norm,
                default=FALSE)
            private$..qq <- jmvcore::OptionBool$new(
                "qq",
                qq,
                default=FALSE)
            private$..eqv <- jmvcore::OptionBool$new(
                "eqv",
                eqv,
                default=FALSE)

            self$.addOption(private$..deps)
            self$.addOption(private$..group)
            self$.addOption(private$..ct1)
            self$.addOption(private$..Ct1Values)
            self$.addOption(private$..ct2)
            self$.addOption(private$..Ct2Values)
            self$.addOption(private$..lint)
            self$.addOption(private$..desc)
            self$.addOption(private$..descPlot)
            self$.addOption(private$..text)
            self$.addOption(private$..norm)
            self$.addOption(private$..qq)
            self$.addOption(private$..eqv)
        }),
    active = list(
        deps = function() private$..deps$value,
        group = function() private$..group$value,
        ct1 = function() private$..ct1$value,
        Ct1Values = function() private$..Ct1Values$value,
        ct2 = function() private$..ct2$value,
        Ct2Values = function() private$..Ct2Values$value,
        lint = function() private$..lint$value,
        desc = function() private$..desc$value,
        descPlot = function() private$..descPlot$value,
        text = function() private$..text$value,
        norm = function() private$..norm$value,
        qq = function() private$..qq$value,
        eqv = function() private$..eqv$value),
    private = list(
        ..deps = NA,
        ..group = NA,
        ..ct1 = NA,
        ..Ct1Values = NA,
        ..ct2 = NA,
        ..Ct2Values = NA,
        ..lint = NA,
        ..desc = NA,
        ..descPlot = NA,
        ..text = NA,
        ..norm = NA,
        ..qq = NA,
        ..eqv = NA)
)

laov1wResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "laov1wResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        anova = function() private$.items[["anova"]],
        desc = function() private$.items[["desc"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]],
        assump = function() private$.items[["assump"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One-Way ANOVA")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="anova",
                title="One-Way ANOVA",
                rows=5,
                clearWith=list(
                    "group",
                    "data",
                    "deps",
                    "Ct1Values",
                    "Ct2Values",
                    "ct1",
                    "ct2"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Model Comparisons", 
                        `type`="text"),
                    list(
                        `name`="S", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="Sc", 
                        `title`="<i>S</i>c", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="text"),
                    list(
                        `name`="F", 
                        `title`="<i>F</i>", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="<i>df</i>", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="<i>p</i>", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "GloverDixon")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="desc",
                title="Group Descriptives",
                rows=0,
                visible="(desc)",
                clearWith=list(
                    "group",
                    "data",
                    "deps"),
                columns=list(
                    list(
                        `name`="dep", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="num", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                visible="(text)",
                clearWith=list(
                    "group",
                    "data",
                    "deps",
                    "Ct1Values",
                    "Ct2Values")))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="<i>LR</i>", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eqv = function() private$.items[["eqv"]],
                    norm = function() private$.items[["norm"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="assump",
                            title="Assumption Checks")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eqv",
                            title="Homogeneity of Variances Test (Levene's)",
                            refs=list(
                                "car",
                                "EdwardsF"),
                            visible="(eqv)",
                            clearWith=list(
                                "group",
                                "dat",
                                "deps"),
                            rows="(deps)",
                            columns=list(
                                list(
                                    `name`="dep", 
                                    `title`="", 
                                    `content`="($key)", 
                                    `type`="text"),
                                list(
                                    `name`="S", 
                                    `title`="<i>S</i>", 
                                    `type`="number"),
                                list(
                                    `name`="F", 
                                    `title`="<i>F</i>", 
                                    `type`="number"),
                                list(
                                    `name`="df", 
                                    `title`="<i>df</i>", 
                                    `type`="text"),
                                list(
                                    `name`="p", 
                                    `title`="<i>p</i>", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="norm",
                            title="Normality Test (Shapiro-Wilk)",
                            visible="(norm)",
                            clearWith=list(
                                "group",
                                "data",
                                "deps"),
                            rows="(deps)",
                            notes=list(
                                `p`="A low p-value suggests a violation of the assumption of normality"),
                            columns=list(
                                list(
                                    `name`="name", 
                                    `title`="", 
                                    `content`="($key)", 
                                    `type`="text"),
                                list(
                                    `name`="w", 
                                    `title`="W", 
                                    `type`="number"),
                                list(
                                    `name`="p", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(deps)",
                clearWith=list(
                    "group",
                    "data",
                    "deps"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        desc = function() private$.items[["desc"]],
                        qq = function() private$.items[["qq"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="desc",
                                height=350,
                                visible="(descPlot)",
                                renderFun=".desc",
                                clearWith=list(
                                    "lint",
                                    "group",
                                    "data",
                                    "deps")))
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="qq",
                                width=350,
                                height=300,
                                requiresData=TRUE,
                                visible="(qq)",
                                renderFun=".qq",
                                clearWith=list()))}))$new(options=options)))}))

laov1wBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "laov1wBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "laov1w",
                version = c(1,0,0),
                options = options,
                results = laov1wResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' One-Way ANOVA
#'
#' The Analysis of Variance (ANOVA) is used to explore the relationship
#' between a continuous dependent variable, and one or more categorical
#' explanatory variables. This 'One-Way ANOVA' is a simplified version of
#' the 'normal' ANOVA, allowing only a single explanatory factor and.
#' dependent variables. Contrasts can be specified whose weights should sum
#' to zero, but do not need to be orthogonal to each other. Support values, 
#' S, represent log likelihood ratio. They are given for each model 
#' comparison. Sc represent Akaike corrected values according to the 
#' number of parameters
#' 
#'
#' @examples
#' data('ToothGrowth')
#' jeva::laov1w(formula = len ~ dose, data = ToothGrowth)
#'
#' #
#' # ONE-WAY ANOVA
#'
#' # Support: One-Way ANOVA (Fisher's assuming equal variances)
#' # ------------------------------------------------------------------------------------------------------------------------
#' #   Model Comparisons                           S              Sc             Param    F             df       p
#' # ------------------------------------------------------------------------------------------------------------------------
#' #   H₀  vs observed means                       -36.4069796    -34.1486064    2, 4      67.415738    2, 57    < .0000001
#' #   Contrast 1 (Linear) vs observed means        -0.7362044      0.4131462    3, 4     133.415383    1, 57    < .0000001
#' #   Contrast 2 (Quadratic) vs observed means    -36.1846993    -35.0353486    3, 4       1.416093    1, 57     0.2389805
#' #   Contrast 1 vs Contrast 2                     35.4484948     35.4484948    3, 3                   1, 1
#' #   Linear vs Non-linear                         35.4484948     35.4484948    3, 3                   1, 1
#' # ------------------------------------------------------------------------------------------------------------------------
#' #   Note. Sc uses Akaike correction for parameters (Param).  Unless specified, Contrast 1 is linear and Contrast 2 is
#' #   quadratic
#' #
#'
#' @param data the data as a data frame
#' @param deps a string naming the dependent variables in \code{data}
#' @param group the grouping or independent variable in \code{data}
#' @param ct1 \code{TRUE} or \code{FALSE} (default), for contrast 1
#' @param Ct1Values a comma-separated list specifying the contrast
#' @param ct2 \code{TRUE} or \code{FALSE} (default), for contrast 2
#' @param Ct2Values a comma-separated list specifying the contrast
#' @param lint likelihood interval given as support values, e.g. 2 or 3,
#'   default = 2
#' @param desc \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @param descPlot \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   plots
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @param norm \code{TRUE} or \code{FALSE} (default), perform Shapiro-Wilk
#'   test of normality
#' @param qq \code{TRUE} or \code{FALSE} (default), provide a Q-Q plot of
#'   residuals
#' @param eqv \code{TRUE} or \code{FALSE} (default), perform Levene's test for
#'   homogeneity of variances
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$anova} \tab \tab \tab \tab \tab a table of the test results \cr
#'   \code{results$desc} \tab \tab \tab \tab \tab a table containing the group descriptives \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$assump$eqv} \tab \tab \tab \tab \tab a table of homogeneity of variances tests \cr
#'   \code{results$assump$norm} \tab \tab \tab \tab \tab a table containing the normality tests \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of groups of plots \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anova$asDF}
#'
#' \code{as.data.frame(results$anova)}
#'
#' @export
laov1w <- function(
    data,
    deps,
    group,
    ct1 = FALSE,
    Ct1Values = "1,-1,...",
    ct2 = FALSE,
    Ct2Values = "1,-1,...",
    lint = 2,
    desc = FALSE,
    descPlot = FALSE,
    text = TRUE,
    norm = FALSE,
    qq = FALSE,
    eqv = FALSE,
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("laov1w requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(deps))
            deps <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                required=TRUE)
        if (missing(group))
            group <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs")
    }

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- laov1wOptions$new(
        deps = deps,
        group = group,
        ct1 = ct1,
        Ct1Values = Ct1Values,
        ct2 = ct2,
        Ct2Values = Ct2Values,
        lint = lint,
        desc = desc,
        descPlot = descPlot,
        text = text,
        norm = norm,
        qq = qq,
        eqv = eqv)

    analysis <- laov1wClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

