
# This file is automatically generated, you probably don't want to edit this

lcorrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            depa = NULL,
            depb = NULL,
            alt = 0,
            lint = 2,
            ciWidth = 95,
            pll = FALSE,
            plt = FALSE,
            line = "none",
            se = FALSE,
            text = TRUE, ...) {

            super$initialize(
                package="jeva",
                name="lcorr",
                requiresData=TRUE,
                ...)

            private$..depa <- jmvcore::OptionVariable$new(
                "depa",
                depa,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..depb <- jmvcore::OptionVariable$new(
                "depb",
                depb,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..alt <- jmvcore::OptionNumber$new(
                "alt",
                alt,
                min=-1,
                max=1,
                default=0)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.99,
                default=95)
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..line <- jmvcore::OptionList$new(
                "line",
                line,
                options=list(
                    "none",
                    "linear",
                    "smooth"),
                default="none")
            private$..se <- jmvcore::OptionBool$new(
                "se",
                se,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)

            self$.addOption(private$..depa)
            self$.addOption(private$..depb)
            self$.addOption(private$..alt)
            self$.addOption(private$..lint)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..pll)
            self$.addOption(private$..plt)
            self$.addOption(private$..line)
            self$.addOption(private$..se)
            self$.addOption(private$..text)
        }),
    active = list(
        depa = function() private$..depa$value,
        depb = function() private$..depb$value,
        alt = function() private$..alt$value,
        lint = function() private$..lint$value,
        ciWidth = function() private$..ciWidth$value,
        pll = function() private$..pll$value,
        plt = function() private$..plt$value,
        line = function() private$..line$value,
        se = function() private$..se$value,
        text = function() private$..text$value),
    private = list(
        ..depa = NA,
        ..depb = NA,
        ..alt = NA,
        ..lint = NA,
        ..ciWidth = NA,
        ..pll = NA,
        ..plt = NA,
        ..line = NA,
        ..se = NA,
        ..text = NA)
)

lcorrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcorrResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lcor = function() private$.items[["lcor"]],
        lcor1 = function() private$.items[["lcor1"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]],
        plotc = function() private$.items[["plotc"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Correlation")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lcor",
                title="Support",
                rows=3,
                clearWith=list(
                    "depa",
                    "depb",
                    "alt",
                    "data"),
                refs=list(
                    "Book"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `type`="number"),
                    list(
                        `name`="rdiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="<i>t</i>", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="<i>df</i>", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="<i>p</i>", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="z", 
                        `type`="number"),
                    list(
                        `name`="pz", 
                        `title`="p(<i>z</i>)", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="lcor1",
                title="Intervals",
                rows=2,
                clearWith=list(
                    "depa",
                    "depb",
                    "alt",
                    "data",
                    "lint",
                    "ciWidth"),
                refs=list(
                    "Pritikin"),
                columns=list(
                    list(
                        `name`="Interval", 
                        `title`="Type of interval", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `title`="<i>r</i>", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                visible="(text)",
                clearWith=list(
                    "depa",
                    "depb",
                    "lint",
                    "alt",
                    "data")))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="<i>LR</i>", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood function with S-{lint} support interval`",
                width=500,
                height=400,
                clearWith=list(
                    "depa",
                    "depb",
                    "alt",
                    "data",
                    "lint"),
                renderFun=".plotc",
                visible="(pll)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Scatterplot",
                width=500,
                height=450,
                clearWith=list(
                    "depa",
                    "depb",
                    "data",
                    "lint",
                    "line",
                    "se"),
                renderFun=".plot",
                visible="(plt)"))}))

lcorrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lcorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "lcorr",
                version = c(1,0,0),
                options = options,
                results = lcorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' Correlation
#'
#' Bivariate correlation analysis where an alternative hypothesis correlation 
#' can be specified. Likelihood support and likelihood based confidence 
#' intervals can be specified. 
#' 
#'
#' @examples
#' data('mtcars')
#' jeva::lcorr(data = mtcars, depa = mpg, depb = cyl)
#'
#' #
#' # CORRELATION
#' #
#' # Support
#' # --------------------------------------------------------------------------------------------------------------------------------------
#' #                                     Value       Difference    S             t            df    p             z            p(z)
#' # --------------------------------------------------------------------------------------------------------------------------------------
#' #   H₀ vs observed correlation        0.000000     0.8521620    -23.166436    -8.919699    30    < .0000001    -6.806825    < .0000001
#' #   Ha versus observed correlation    0.000000     0.8521620    -23.166436                                     -6.806825    < .0000001
#' #   Ha vs H₀                                       0.0000000      0.000000
#' # --------------------------------------------------------------------------------------------------------------------------------------
#' #   Note. The last column p(z) gives the p value for the preceding z value
#' #
#' #
#' # Intervals
#' # -------------------------------------------------------------------------
#' #   Type of interval      Level    r             Lower         Upper
#' # -------------------------------------------------------------------------
#' #   Support               2        -0.8521620    -0.9268248    -0.7126780
#' #   Likelihood-based a    95\%      -0.8521620    -0.9257632    -0.7163143
#' # -------------------------------------------------------------------------
#' #
#' #
#'
#' @param data the data as a data frame
#' @param depa the first variable from \code{data}, plotted on vertical axis,
#'   variable must be numeric
#' @param depb the second variable from \code{data}, plotted on horizontal
#'   axis, variable must be numeric
#' @param alt a specified value for the alternative hypothesis, range -1 to
#'   +1, default 0
#' @param lint likelihood interval given as support value, e.g. 2 or 3,
#'   default = 2
#' @param ciWidth a number between 50 and 99.9 (default: 95), width of the
#'   confidence intervals to provide
#' @param pll plot the likelihood function displaying observed correlation,
#'   alternative hypothesis and support interval
#' @param plt \code{TRUE} or \code{FALSE} (default), do a scatter plot of the
#'   data
#' @param line \code{none} (default), \code{linear}, or \code{smooth}, provide
#'   respectively no regression line,  a linear regression line, or a smoothed
#'   regression line
#' @param se \code{TRUE} or \code{FALSE} (default), show the standard error
#'   for the regression line
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lcor} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lcor1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lcor$asDF}
#'
#' \code{as.data.frame(results$lcor)}
#'
#' @export
lcorr <- function(
    data,
    depa,
    depb,
    alt = 0,
    lint = 2,
    ciWidth = 95,
    pll = FALSE,
    plt = FALSE,
    line = "none",
    se = FALSE,
    text = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lcorr requires jmvcore to be installed (restart may be required)")

    if ( ! missing(depa)) depa <- jmvcore::resolveQuo(jmvcore::enquo(depa))
    if ( ! missing(depb)) depb <- jmvcore::resolveQuo(jmvcore::enquo(depb))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(depa), depa, NULL),
            `if`( ! missing(depb), depb, NULL))


    options <- lcorrOptions$new(
        depa = depa,
        depb = depb,
        alt = alt,
        lint = lint,
        ciWidth = ciWidth,
        pll = pll,
        plt = plt,
        line = line,
        se = se,
        text = text)

    analysis <- lcorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

