
# This file is automatically generated, you probably don't want to edit this

ldiagOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ldiagOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            nulsens = 0.5,
            nulspec = 0.5,
            pprob = FALSE,
            ppval = 0.1,
            lint = 2,
            ciWidth = 95,
            correction = "ob",
            fagan = FALSE,
            pll = FALSE,
            plotype = "lplot",
            supplot = -10,
            choice = "sens_plot",
            varA = FALSE,
            cc = FALSE,
            text = TRUE,
            obs = TRUE,
            exp = FALSE,
            pcRow = FALSE,
            pcCol = FALSE,
            pcTot = FALSE,
            barplot = FALSE,
            yaxis = "ycounts",
            yaxisPc = "total_pc",
            xaxis = "xrows",
            bartype = "dodge", ...) {

            super$initialize(
                package="jeva",
                name="ldiag",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..nulsens <- jmvcore::OptionNumber$new(
                "nulsens",
                nulsens,
                min=0,
                max=100000000000,
                default=0.5)
            private$..nulspec <- jmvcore::OptionNumber$new(
                "nulspec",
                nulspec,
                min=0,
                max=1,
                default=0.5)
            private$..pprob <- jmvcore::OptionBool$new(
                "pprob",
                pprob,
                default=FALSE)
            private$..ppval <- jmvcore::OptionNumber$new(
                "ppval",
                ppval,
                min=0,
                max=1,
                default=0.1)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9999,
                default=95)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "nc",
                    "ob",
                    "aic"),
                default="ob")
            private$..fagan <- jmvcore::OptionBool$new(
                "fagan",
                fagan,
                default=FALSE)
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)
            private$..plotype <- jmvcore::OptionList$new(
                "plotype",
                plotype,
                options=list(
                    "lplot",
                    "logplot"),
                default="lplot")
            private$..supplot <- jmvcore::OptionNumber$new(
                "supplot",
                supplot,
                min=-200,
                max=-1,
                default=-10)
            private$..choice <- jmvcore::OptionList$new(
                "choice",
                choice,
                options=list(
                    "sens_plot",
                    "spec_plot"),
                default="sens_plot")
            private$..varA <- jmvcore::OptionBool$new(
                "varA",
                varA,
                default=FALSE)
            private$..cc <- jmvcore::OptionBool$new(
                "cc",
                cc,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)
            private$..obs <- jmvcore::OptionBool$new(
                "obs",
                obs,
                default=TRUE)
            private$..exp <- jmvcore::OptionBool$new(
                "exp",
                exp,
                default=FALSE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
            private$..pcTot <- jmvcore::OptionBool$new(
                "pcTot",
                pcTot,
                default=FALSE)
            private$..barplot <- jmvcore::OptionBool$new(
                "barplot",
                barplot,
                default=FALSE)
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "ycounts",
                    "ypc"),
                default="ycounts")
            private$..yaxisPc <- jmvcore::OptionList$new(
                "yaxisPc",
                yaxisPc,
                options=list(
                    "total_pc",
                    "column_pc",
                    "row_pc"),
                default="total_pc")
            private$..xaxis <- jmvcore::OptionList$new(
                "xaxis",
                xaxis,
                options=list(
                    "xrows",
                    "xcols"),
                default="xrows")
            private$..bartype <- jmvcore::OptionList$new(
                "bartype",
                bartype,
                options=list(
                    "dodge",
                    "stack"),
                default="dodge")

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..nulsens)
            self$.addOption(private$..nulspec)
            self$.addOption(private$..pprob)
            self$.addOption(private$..ppval)
            self$.addOption(private$..lint)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..correction)
            self$.addOption(private$..fagan)
            self$.addOption(private$..pll)
            self$.addOption(private$..plotype)
            self$.addOption(private$..supplot)
            self$.addOption(private$..choice)
            self$.addOption(private$..varA)
            self$.addOption(private$..cc)
            self$.addOption(private$..text)
            self$.addOption(private$..obs)
            self$.addOption(private$..exp)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..pcTot)
            self$.addOption(private$..barplot)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..yaxisPc)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..bartype)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        nulsens = function() private$..nulsens$value,
        nulspec = function() private$..nulspec$value,
        pprob = function() private$..pprob$value,
        ppval = function() private$..ppval$value,
        lint = function() private$..lint$value,
        ciWidth = function() private$..ciWidth$value,
        correction = function() private$..correction$value,
        fagan = function() private$..fagan$value,
        pll = function() private$..pll$value,
        plotype = function() private$..plotype$value,
        supplot = function() private$..supplot$value,
        choice = function() private$..choice$value,
        varA = function() private$..varA$value,
        cc = function() private$..cc$value,
        text = function() private$..text$value,
        obs = function() private$..obs$value,
        exp = function() private$..exp$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value,
        pcTot = function() private$..pcTot$value,
        barplot = function() private$..barplot$value,
        yaxis = function() private$..yaxis$value,
        yaxisPc = function() private$..yaxisPc$value,
        xaxis = function() private$..xaxis$value,
        bartype = function() private$..bartype$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..nulsens = NA,
        ..nulspec = NA,
        ..pprob = NA,
        ..ppval = NA,
        ..lint = NA,
        ..ciWidth = NA,
        ..correction = NA,
        ..fagan = NA,
        ..pll = NA,
        ..plotype = NA,
        ..supplot = NA,
        ..choice = NA,
        ..varA = NA,
        ..cc = NA,
        ..text = NA,
        ..obs = NA,
        ..exp = NA,
        ..pcRow = NA,
        ..pcCol = NA,
        ..pcTot = NA,
        ..barplot = NA,
        ..yaxis = NA,
        ..yaxisPc = NA,
        ..xaxis = NA,
        ..bartype = NA)
)

ldiagResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ldiagResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        stats = function() private$.items[["stats"]],
        text = function() private$.items[["text"]],
        ctt = function() private$.items[["ctt"]],
        cttsens = function() private$.items[["cttsens"]],
        cttspec = function() private$.items[["cttspec"]],
        ctt3 = function() private$.items[["ctt3"]],
        plotc = function() private$.items[["plotc"]],
        plot1 = function() private$.items[["plot1"]],
        barplot = function() private$.items[["barplot"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Diagnostic Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="freqs",
                title="Contingency Tables",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="stats",
                title="Diagnostic Statistics",
                rows=1,
                refs=list(
                    "Youden"),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "nulsens",
                    "nulspec",
                    "ppval",
                    "pprob"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="LR", 
                        `title`="LR", 
                        `type`="number"),
                    list(
                        `name`="NLR", 
                        `title`="Neg LR", 
                        `type`="number"),
                    list(
                        `name`="Acc", 
                        `title`="Accuracy", 
                        `type`="number"),
                    list(
                        `name`="OR", 
                        `title`="Odds Ratio", 
                        `type`="number"),
                    list(
                        `name`="Prev", 
                        `title`="Prevalence", 
                        `type`="number"),
                    list(
                        `name`="PPV", 
                        `title`="PPV", 
                        `type`="number"),
                    list(
                        `name`="NPV", 
                        `title`="NPV", 
                        `type`="number"),
                    list(
                        `name`="Youd", 
                        `title`="Youden's index J", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt",
                title="Diagnostic analyses",
                rows=2,
                refs=list(
                    "Book",
                    "Hawass",
                    "Edwards_OR"),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "nulsens",
                    "nulspec"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="ordiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="number"),
                    list(
                        `name`="G", 
                        `title`="G", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cttsens",
                title="Intervals for Sensitivity",
                rows=2,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "lint",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="Interval", 
                        `title`="Type of interval", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `type`="text"),
                    list(
                        `name`="sens", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cttspec",
                title="Intervals for Specificity",
                rows=2,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "lint",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="Interval", 
                        `title`="Type of interval", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `type`="text"),
                    list(
                        `name`="spec", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number", 
                        `refs`=list(
                            "Pritikin")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt3",
                title="Variance analysis",
                visible="(varA)",
                rows="1 - rows - cols - counts - data - cc",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Sv", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="X2", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="dfv", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="pv", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pv1", 
                        `title`="1 - p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "EdwardsVA")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood curve for Sensitivity/Specificity with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "lint",
                    "ciWidth",
                    "nulsens",
                    "nulspec",
                    "plotype",
                    "supplot",
                    "choice"),
                visible="(pll)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot1",
                title="Fagan Nomogram",
                width=600,
                height=450,
                renderFun=".plot1",
                requiresData=TRUE,
                visible="(fagan)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "prev",
                    "pprob",
                    "ppval"),
                refs=list(
                    "Fagan")))
            self$add(jmvcore::Image$new(
                options=options,
                name="barplot",
                title="Plots",
                width=450,
                height=400,
                renderFun=".barPlot",
                visible="(barplot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "barplot",
                    "yaxis",
                    "yaxisPc",
                    "xaxis",
                    "bartype",
                    "pcTot",
                    "pcCol",
                    "pcRow")))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                visible="(text)",
                refs=list(
                    "ILR"),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "lint",
                    "ciWidth",
                    "nulsens",
                    "nulspec")))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="LR", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))}))

ldiagBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ldiagBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "ldiag",
                version = c(1,0,0),
                options = options,
                results = ldiagResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Diagnostic Test
#'
#' Analysis of a 2 x 2 contingency table using diagnostic test
#' 
#'
#' @examples
#' dat <- data.frame(
#'   CT_scan = c('+', '+', '-', '-'),
#'   Final_diagnosis = c('+', '-','+', '-'),
#'   count = c(52, 11, 37, 100),
#'   check.names=FALSE)
#'
#'   jeva::ldiag(formula = count ~ CT_scan:Final_diagnosis, data = dat, text = FALSE)
#'
#' @param data the data as a data frame
#' @param rows the variable to use as the rows in the contingency table (not
#'   necessary when providing a formula, see the examples)
#' @param cols the variable to use as the columns in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param counts the variable to use as the counts in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param nulsens value for the null hypothesis, default = 0.5
#' @param nulspec value for the alternative hypothesis, default = 0.5
#' @param pprob \code{TRUE} or \code{FALSE} (default), select the prior
#'   probability or prevalence
#' @param ppval To set the prior probability/prevalence
#' @param lint likelihood interval given as support value, e.g. 2 or 3,
#'   default = 2
#' @param ciWidth a number between 50 and 99.9 (default: 95), width of the
#'   confidence intervals to provide
#' @param correction correction for parameters, none, Occam's bonus (default)
#'   or AIC
#' @param fagan .
#' @param pll \code{TRUE} or \code{FALSE} (default), give the likelihood
#'   function showing null hypothesis (black line),  alternative hypothesis
#'   (blue line), mean (dashed line), and specified support interval
#'   (horizontal red line)
#' @param plotype choose type of plot, likelihood function (default), support
#'   function
#' @param supplot To set the minimum likelihood display value in plot, in log
#'   units (default = -10)  affects the x-axis range
#' @param choice choose to show likelihood function for sensitivity (default)
#'   or specificity
#' @param varA \code{TRUE} or \code{FALSE} (default), perform variance
#'   analysis for null and alternative hypothesis
#' @param cc \code{TRUE} or \code{FALSE} (default), use continuity correction
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @param obs \code{TRUE} or \code{FALSE} (default), provide the observed
#'   counts
#' @param exp \code{TRUE} or \code{FALSE} (default), provide the expected
#'   counts
#' @param pcRow \code{TRUE} or \code{FALSE} (default), provide row percentages
#' @param pcCol \code{TRUE} or \code{FALSE} (default), provide column
#'   percentages
#' @param pcTot \code{TRUE} or \code{FALSE} (default), provide total
#'   percentages
#' @param barplot \code{TRUE} or \code{FALSE} (default), show barplots
#' @param yaxis ycounts (default) or ypc. Use respectively \code{counts} or
#'   \code{percentages} for the bar plot y-axis
#' @param yaxisPc total_pc (default), column_pc, or row_pc. Use respectively
#'   percentages \code{of total}, \code{within columns}, or \code{within rows}
#'   for the bar plot y-axis.
#' @param xaxis rows (default), or columns in bar plot X axis
#' @param bartype stack or side by side (default), barplot type
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$stats} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ctt} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cttsens} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cttspec} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ctt3} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$barplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqs$asDF}
#'
#' \code{as.data.frame(results$freqs)}
#'
#' @export
ldiag <- function(
    data,
    rows,
    cols,
    counts = NULL,
    nulsens = 0.5,
    nulspec = 0.5,
    pprob = FALSE,
    ppval = 0.1,
    lint = 2,
    ciWidth = 95,
    correction = "ob",
    fagan = FALSE,
    pll = FALSE,
    plotype = "lplot",
    supplot = -10,
    choice = "sens_plot",
    varA = FALSE,
    cc = FALSE,
    text = TRUE,
    obs = TRUE,
    exp = FALSE,
    pcRow = FALSE,
    pcCol = FALSE,
    pcTot = FALSE,
    barplot = FALSE,
    yaxis = "ycounts",
    yaxisPc = "total_pc",
    xaxis = "xrows",
    bartype = "dodge",
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ldiag requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(counts))
            counts <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                type="vars",
                subset="1")
        if (missing(rows))
            rows <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="1")
        if (missing(cols))
            cols <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="2")
    }

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ldiagOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        nulsens = nulsens,
        nulspec = nulspec,
        pprob = pprob,
        ppval = ppval,
        lint = lint,
        ciWidth = ciWidth,
        correction = correction,
        fagan = fagan,
        pll = pll,
        plotype = plotype,
        supplot = supplot,
        choice = choice,
        varA = varA,
        cc = cc,
        text = text,
        obs = obs,
        exp = exp,
        pcRow = pcRow,
        pcCol = pcCol,
        pcTot = pcTot,
        barplot = barplot,
        yaxis = yaxis,
        yaxisPc = yaxisPc,
        xaxis = xaxis,
        bartype = bartype)

    analysis <- ldiagClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

