
# This file is automatically generated, you probably don't want to edit this

lregOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lregOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            pred = NULL,
            correction = "ob",
            plt = FALSE,
            lin = TRUE,
            quad = FALSE,
            cub = FALSE,
            quart = FALSE,
            lint = 2,
            text = TRUE, ...) {

            super$initialize(
                package="jeva",
                name="lreg",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..pred <- jmvcore::OptionVariable$new(
                "pred",
                pred,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "nc",
                    "ob",
                    "aic"),
                default="ob")
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..lin <- jmvcore::OptionBool$new(
                "lin",
                lin,
                default=TRUE)
            private$..quad <- jmvcore::OptionBool$new(
                "quad",
                quad,
                default=FALSE)
            private$..cub <- jmvcore::OptionBool$new(
                "cub",
                cub,
                default=FALSE)
            private$..quart <- jmvcore::OptionBool$new(
                "quart",
                quart,
                default=FALSE)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..pred)
            self$.addOption(private$..correction)
            self$.addOption(private$..plt)
            self$.addOption(private$..lin)
            self$.addOption(private$..quad)
            self$.addOption(private$..cub)
            self$.addOption(private$..quart)
            self$.addOption(private$..lint)
            self$.addOption(private$..text)
        }),
    active = list(
        dep = function() private$..dep$value,
        pred = function() private$..pred$value,
        correction = function() private$..correction$value,
        plt = function() private$..plt$value,
        lin = function() private$..lin$value,
        quad = function() private$..quad$value,
        cub = function() private$..cub$value,
        quart = function() private$..quart$value,
        lint = function() private$..lint$value,
        text = function() private$..text$value),
    private = list(
        ..dep = NA,
        ..pred = NA,
        ..correction = NA,
        ..plt = NA,
        ..lin = NA,
        ..quad = NA,
        ..cub = NA,
        ..quart = NA,
        ..lint = NA,
        ..text = NA)
)

lregResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lregResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lreg = function() private$.items[["lreg"]],
        coef = function() private$.items[["coef"]],
        plot = function() private$.items[["plot"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Polynomial Regression")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lreg",
                title="Support",
                rows=4,
                clearWith=list(
                    "dep",
                    "pred",
                    "data",
                    "correction"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Model Comparisons", 
                        `type`="text"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="number"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                refs=list(
                    "Edwards_OR",
                    "Glover_Tut")))
            self$add(jmvcore::Table$new(
                options=options,
                name="coef",
                title="`Model Coefficients - ${ dep }`",
                clearWith=list(
                    "dep",
                    "lint",
                    "pred",
                    "data"),
                rows=5,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Scatterplot with Model fits",
                width=500,
                height=450,
                renderFun=".plot",
                visible="(plt)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                visible="(text)",
                clearWith=list(
                    "dep",
                    "lint",
                    "pred",
                    "data",
                    "correction")))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="LR", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))}))

lregBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lregBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "lreg",
                version = c(1,0,0),
                options = options,
                results = lregResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Polynomial Regression
#'
#' Polynomial regression of two variables where different orders are compared. 
#' Akaike corrected support values are calculated hierarchically. R-squared 
#' and AIC values are given. P values are calculated in the usual way from the 
#' residual mean sums of squares from the highest polynomial in the model, but 
#' these are not comparable with the support values. Model coefficients are 
#' given with their specified likelihood support level. Plots for different 
#' polynomial orders can be plotted. 
#' 
#'
#' @examples
#' data('mtcars')
#' jeva::lreg(data = mtcars, dep = mpg, pred = hp, text = FALSE)
#'
#' #
#' # POLYNOMIAL REGRESSION
#' #
#' # Support
#' # --------------------------------------------------------------------------------------------------
#' #   Model Comparisons          S              Param    R²           AIC         df       p
#' # --------------------------------------------------------------------------------------------------
#' #   H₀ vs Linear               -14.2584436     2, 3    0.6024373    181.2386    1, 30    0.0000002
#' #   Quadratic vs Linear          7.3181632     3, 4    0.7561100    167.6023    1, 27    0.0002868
#' #   Cubic vs Lower Orders       -0.2044684     4, 5    0.7605735    169.0112    1, 27    0.4840465
#' #   Quartic vs Lower Orders     -0.4948111     5, 6    0.7606511    171.0009    1, 27    0.9261317
#' # --------------------------------------------------------------------------------------------------
#' #   Note. S uses Occam's Bonus correction for parameters (Param). S is calculated hierarchically
#' #   from all remaining SSq, while p values are calculated using residual MSq from the highest
#' #   polynomial model.
#' #
#' #
#' # Model Coefficients - mpg
#' # ----------------------------------------------------------------------------------------------------------
#' #   Predictor    Estimate        SE              S               Lower           Upper           p
#' # ----------------------------------------------------------------------------------------------------------
#' #   Intercept    45.359415905    13.557249652    -5.549534400    19.654183298    71.064648512    0.0024227
#' #   Linear       -0.328488135     0.382186016    -0.431888228    -1.053132196     0.396155925    0.3976331
#' #   Quadratic     0.001246952     0.003652374    -0.068923891    -0.005678134     0.008172038    0.7354387
#' #   Cubic        -2.185873e-6     1.411330e-5    -0.014208762    -2.894540e-5     2.457366e-5    0.8780676
#' #   Quartic       1.756358e-9     1.876800e-8    -0.005188909    -3.382872e-8     3.734143e-8    0.9261317
#' # ----------------------------------------------------------------------------------------------------------
#' #
#'
#' @param data the data as a data frame
#' @param dep the dependent variable from \code{data}, variable must be
#'   numeric
#' @param pred the predictor variable, must be numeric
#' @param correction correction for parameters, none, Occam's bonus (default)
#'   or AIC
#' @param plt \code{TRUE} or \code{FALSE} (default), do a scatter plot of the
#'   data
#' @param lin \code{TRUE} (default) or \code{FALSE}, plot line for linear
#'   relationship
#' @param quad \code{TRUE} or \code{FALSE} (default), plot curve for quadratic
#'   relationship
#' @param cub \code{TRUE} or \code{FALSE} (default), plot curve for cubic
#'   relationship
#' @param quart \code{TRUE} or \code{FALSE} (default), plot curve for quartic
#'   relationship
#' @param lint a number between 1 and 100 (default: 2) specifying the
#'   likelihood support interval width
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lreg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coef} \tab \tab \tab \tab \tab a table of model coefficients \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lreg$asDF}
#'
#' \code{as.data.frame(results$lreg)}
#'
#' @export
lreg <- function(
    data,
    dep,
    pred,
    correction = "ob",
    plt = FALSE,
    lin = TRUE,
    quad = FALSE,
    cub = FALSE,
    quart = FALSE,
    lint = 2,
    text = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lreg requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(pred)) pred <- jmvcore::resolveQuo(jmvcore::enquo(pred))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(pred), pred, NULL))


    options <- lregOptions$new(
        dep = dep,
        pred = pred,
        correction = correction,
        plt = plt,
        lin = lin,
        quad = quad,
        cub = cub,
        quart = quart,
        lint = lint,
        text = text)

    analysis <- lregClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

