
# This file is automatically generated, you probably don't want to edit this

LregOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LregOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            pred = NULL,
            plt = FALSE,
            lin = TRUE,
            quad = FALSE,
            cub = FALSE,
            quart = FALSE,
            lint = 2,
            text = TRUE, ...) {

            super$initialize(
                package="jeva",
                name="Lreg",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..pred <- jmvcore::OptionVariable$new(
                "pred",
                pred,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..lin <- jmvcore::OptionBool$new(
                "lin",
                lin,
                default=TRUE)
            private$..quad <- jmvcore::OptionBool$new(
                "quad",
                quad,
                default=FALSE)
            private$..cub <- jmvcore::OptionBool$new(
                "cub",
                cub,
                default=FALSE)
            private$..quart <- jmvcore::OptionBool$new(
                "quart",
                quart,
                default=FALSE)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..pred)
            self$.addOption(private$..plt)
            self$.addOption(private$..lin)
            self$.addOption(private$..quad)
            self$.addOption(private$..cub)
            self$.addOption(private$..quart)
            self$.addOption(private$..lint)
            self$.addOption(private$..text)
        }),
    active = list(
        dep = function() private$..dep$value,
        pred = function() private$..pred$value,
        plt = function() private$..plt$value,
        lin = function() private$..lin$value,
        quad = function() private$..quad$value,
        cub = function() private$..cub$value,
        quart = function() private$..quart$value,
        lint = function() private$..lint$value,
        text = function() private$..text$value),
    private = list(
        ..dep = NA,
        ..pred = NA,
        ..plt = NA,
        ..lin = NA,
        ..quad = NA,
        ..cub = NA,
        ..quart = NA,
        ..lint = NA,
        ..text = NA)
)

LregResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LregResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lreg = function() private$.items[["lreg"]],
        coef = function() private$.items[["coef"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Polynomial Regression")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lreg",
                title="Support",
                rows=4,
                clearWith=list(
                    "dep",
                    "pred",
                    "data"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Model Comparisons", 
                        `type`="text"),
                    list(
                        `name`="S", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="Sc", 
                        `title`="<i>S</i>c", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `type`="number"),
                    list(
                        `name`="r2", 
                        `title`="<i>R</i>\u00B2", 
                        `type`="number"),
                    list(
                        `name`="aic", 
                        `title`="<i>AIC</i>", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="<i>df</i>", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="<i>p</i>", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coef",
                title="`Model Coefficients - ${ dep }`",
                clearWith=list(
                    "dep",
                    "lint",
                    "pred",
                    "data"),
                rows=5,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="<i>p</i>", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                visible="(text)",
                clearWith=list(
                    "dep",
                    "lint",
                    "pred",
                    "data")))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="<i>LR</i>", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Scatterplot with Model fits",
                width=500,
                height=450,
                renderFun=".plot",
                visible="(plt)"))}))

LregBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "LregBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "Lreg",
                version = c(1,0,0),
                options = options,
                results = LregResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' Polynomial Regression
#'
#' Polynomial regression of two variables where different orders are compared. 
#' Akaike corrected support values are calculated hierarchically. R-squared 
#' and AIC values are given. P values are calculated in the usual way from the 
#' residual mean sums of squares from the highest polynomial in the model, but 
#' these are not comparable with the support values. Model coefficients are 
#' given with their specified likelihood support level. Plots for different 
#' polynomial orders can be plotted. 
#' 
#'
#' @examples
#' data('Prestige', package='carData')
#' jeva::Lreg(data = Prestige, dep = income, pred = education)
#'
#' #
#' # POLYNOMIAL REGRESSION
#'
#' # Support
#' # ------------------------------------------------------------------------------------------------------------------
#' #   Model Comparisons          S             Sc             Param    R²           AIC         df        p
#' # ------------------------------------------------------------------------------------------------------------------
#' #   H₀ vs Linear               -20.699042    -19.6990419     2, 3    0.3335989    1957.218    1, 100    < .0000001
#' #   Quadratic vs Linear          3.931699      2.9316990     3, 4    0.3830428    1951.355     1, 97     0.0048170
#' #   Cubic vs Lower Orders        2.078532      1.0785316     4, 5    0.4076818    1949.198     1, 97     0.0443862
#' #   Quartic vs Lower Orders      1.420330      0.4203303     5, 6    0.4239500    1948.357     1, 97     0.1011348
#' # ------------------------------------------------------------------------------------------------------------------
#' #   Note. S is calculated hierarchically from all remaining SSq, while p values are calculated using residual
#' #   MSq from the highest polynomial model.  Sc uses Akaike correction for parameters (Param)
#' #
#' #
#' # Model Coefficients - income
#' # -----------------------------------------------------------------------------------------------------------
#' #   Predictor    Estimate        SE               S             Lower             Upper           p
#' # -----------------------------------------------------------------------------------------------------------
#' #   Intercept    124417.37122    100841.862332    -0.7941328     -74205.080195    323039.82263    0.2202634
#' #   Linear       -50575.91460     38772.519128    -0.8868626    -126943.929025     25792.09981    0.1951747
#' #   Quadratic      7733.55748      5452.012647    -1.0470743      -3004.960159     18472.07511    0.1592564
#' #   Cubic          -509.11758       332.656469    -1.2168895      -1164.332014       146.09685    0.1291576
#' #   Quartic          12.31439         7.440234    -1.4203303         -2.340217        26.96899    0.1011348
#' # -----------------------------------------------------------------------------------------------------------
#' #
#' #
#'
#' @param data the data as a data frame
#' @param dep the dependent variable from \code{data}, variable must be
#'   numeric
#' @param pred the predictor variable, must be numeric
#' @param plt \code{TRUE} or \code{FALSE} (default), do a scatter plot of the
#'   data
#' @param lin \code{TRUE} (default) or \code{FALSE}, plot line for linear
#'   relationship
#' @param quad \code{TRUE} or \code{FALSE} (default), plot curve for quadratic
#'   relationship
#' @param cub \code{TRUE} or \code{FALSE} (default), plot curve for cubic
#'   relationship
#' @param quart \code{TRUE} or \code{FALSE} (default), plot curve for quartic
#'   relationship
#' @param lint a number between 1 and 100 (default: 2) specifying the
#'   likelihood support interval width
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lreg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coef} \tab \tab \tab \tab \tab a table of model coefficients \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lreg$asDF}
#'
#' \code{as.data.frame(results$lreg)}
#'
#' @export
Lreg <- function(
    data,
    dep,
    pred,
    plt = FALSE,
    lin = TRUE,
    quad = FALSE,
    cub = FALSE,
    quart = FALSE,
    lint = 2,
    text = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Lreg requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(pred)) pred <- jmvcore::resolveQuo(jmvcore::enquo(pred))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(pred), pred, NULL))


    options <- LregOptions$new(
        dep = dep,
        pred = pred,
        plt = plt,
        lin = lin,
        quad = quad,
        cub = cub,
        quart = quart,
        lint = lint,
        text = text)

    analysis <- LregClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

