
# This file is automatically generated, you probably don't want to edit this

lrttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lrttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            depa = NULL,
            depb = NULL,
            nul = 0,
            alt = 0,
            lint = 2,
            correction = "ob",
            pll = FALSE,
            plotype = "lplot",
            supplot = -10,
            dtab = FALSE,
            plt = FALSE,
            text = TRUE, ...) {

            super$initialize(
                package="jeva",
                name="lrttest",
                requiresData=TRUE,
                ...)

            private$..depa <- jmvcore::OptionVariable$new(
                "depa",
                depa,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..depb <- jmvcore::OptionVariable$new(
                "depb",
                depb,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..nul <- jmvcore::OptionNumber$new(
                "nul",
                nul,
                min=-100000000000,
                max=100000000000,
                default=0)
            private$..alt <- jmvcore::OptionNumber$new(
                "alt",
                alt,
                min=-100000000000,
                max=100000000000,
                default=0)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "nc",
                    "ob",
                    "aic"),
                default="ob")
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)
            private$..plotype <- jmvcore::OptionList$new(
                "plotype",
                plotype,
                options=list(
                    "lplot",
                    "logplot"),
                default="lplot")
            private$..supplot <- jmvcore::OptionNumber$new(
                "supplot",
                supplot,
                min=-100,
                max=-1,
                default=-10)
            private$..dtab <- jmvcore::OptionBool$new(
                "dtab",
                dtab,
                default=FALSE)
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)

            self$.addOption(private$..depa)
            self$.addOption(private$..depb)
            self$.addOption(private$..nul)
            self$.addOption(private$..alt)
            self$.addOption(private$..lint)
            self$.addOption(private$..correction)
            self$.addOption(private$..pll)
            self$.addOption(private$..plotype)
            self$.addOption(private$..supplot)
            self$.addOption(private$..dtab)
            self$.addOption(private$..plt)
            self$.addOption(private$..text)
        }),
    active = list(
        depa = function() private$..depa$value,
        depb = function() private$..depb$value,
        nul = function() private$..nul$value,
        alt = function() private$..alt$value,
        lint = function() private$..lint$value,
        correction = function() private$..correction$value,
        pll = function() private$..pll$value,
        plotype = function() private$..plotype$value,
        supplot = function() private$..supplot$value,
        dtab = function() private$..dtab$value,
        plt = function() private$..plt$value,
        text = function() private$..text$value),
    private = list(
        ..depa = NA,
        ..depb = NA,
        ..nul = NA,
        ..alt = NA,
        ..lint = NA,
        ..correction = NA,
        ..pll = NA,
        ..plotype = NA,
        ..supplot = NA,
        ..dtab = NA,
        ..plt = NA,
        ..text = NA)
)

lrttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lrttestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lrttest = function() private$.items[["lrttest"]],
        lrttest2 = function() private$.items[["lrttest2"]],
        lrttestd = function() private$.items[["lrttestd"]],
        plot = function() private$.items[["plot"]],
        plotc = function() private$.items[["plotc"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Paired Samples T-Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lrttest",
                title="Support",
                clearWith=list(
                    "depb",
                    "depa",
                    "nul",
                    "alt",
                    "data",
                    "correction"),
                rows=3,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `type`="number"),
                    list(
                        `name`="mdiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="sed", 
                        `title`="SE difference", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `title`="Param", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "Edwards_OR",
                            "Glover_Tut")))))
            self$add(jmvcore::Table$new(
                options=options,
                name="lrttest2",
                title="Support Interval for mean difference",
                clearWith=list(
                    "depb",
                    "depa",
                    "nul",
                    "alt",
                    "data",
                    "lint"),
                rows=1,
                columns=list(
                    list(
                        `name`="diff", 
                        `title`="Mean difference", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="lrttestd",
                title="Group Descriptives",
                visible="(dtab)",
                clearWith=list(
                    "depb",
                    "depa",
                    "data"),
                rows=2,
                columns=list(
                    list(
                        `name`="gp", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="N", 
                        `type`="number"),
                    list(
                        `name`="Mean", 
                        `type`="number"),
                    list(
                        `name`="Median", 
                        `type`="number"),
                    list(
                        `name`="SD", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="`Mean difference with S-{lint} support interval`",
                width=400,
                height=300,
                renderFun=".plot",
                clearWith=list(
                    "depb",
                    "depa",
                    "data",
                    "lint"),
                visible="(plt)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood curve with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                clearWith=list(
                    "depb",
                    "depa",
                    "nul",
                    "alt",
                    "data",
                    "lint",
                    "logplot",
                    "lplot",
                    "plotype",
                    "supplot"),
                visible="(pll)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                clearWith=list(
                    "depb",
                    "depa",
                    "nul",
                    "alt",
                    "data",
                    "lint",
                    "correction"),
                visible="(text)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="LR", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))}))

lrttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lrttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "lrttest",
                version = c(1,0,0),
                options = options,
                results = lrttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Paired Samples T-Test
#'
#' Related samples analysis where null and alternative hypotheses can be 
#' specified. Likelihood interval support level can be specified and plotted 
#' with the mean difference. A likelihood function for the mean difference can 
#' be plotted. 
#' 
#'
#' @examples
#' data('bugs', package = 'jmv')
#' jeva::lrttest(data = bugs, depa = LDLF, depb = LDHF, text = FALSE)
#'
#' #
#' # PAIRED SAMPLES T-TEST
#' #
#' # Support
#' #                                     Value       Difference    SE difference    S              Param    t            df          p
#' # --------------------------------------------------------------------------------------------------------------------------------------------
#' #   H₀ vs observed mean difference    0.000000      1.664835        0.2504032    -17.6796259     2, 3    -6.648618    90.00000    < .0000001
#' #   Ha vs observed mean difference    0.000000      1.664835        0.2504032    -18.1796259     3, 3    -6.648618    90.00000    < .0000001
#' #   Ha vs H₀                                        0.000000        0.2504032     -0.5000000     3, 2
#' # --------------------------------------------------------------------------------------------------------------------------------------------
#' #   Note. S uses Occam's Bonus correction for parameters (Param)
#' #
#' #
#' # Support Interval for mean difference
#' # ---------------------------------------------
#' #   Mean difference    Lower        Upper
#' # ---------------------------------------------
#' #         -1.664835    -2.168406    -1.161265
#' # ---------------------------------------------
#' #
#'
#' @param data the data as a data frame
#' @param depa a (non-empty) numeric vector of data values for 1st group
#' @param depb a (non-empty) numeric vector of data values for 2nd group
#' @param nul difference value for the null hypothesis, default = 0
#' @param alt difference value for an alternative hypothesis, default = 0
#' @param lint likelihood interval given as support value, e.g. 2 or 3,
#'   default = 2
#' @param correction correction for parameters, none, Occam's bonus (default)
#'   or AIC
#' @param pll \code{TRUE} or \code{FALSE} (default), give the likelihood or
#'   log likelihood function showing  null hypothesis (black line), alternative
#'   hypothesis (blue line), mean (dashed line),  and specified support interval
#'   (horizontal red line)
#' @param plotype choose type of plot, likelihood function (default), support
#'   function
#' @param supplot To set the minimum likelihood display value in plot, in log
#'   units (default = -10)  affects the x-axis range
#' @param dtab \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @param plt \code{TRUE} or \code{FALSE} (default), give a plot of means with
#'   specified support intervals
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lrttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lrttest2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lrttestd} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lrttest$asDF}
#'
#' \code{as.data.frame(results$lrttest)}
#'
#' @export
lrttest <- function(
    data,
    depa,
    depb,
    nul = 0,
    alt = 0,
    lint = 2,
    correction = "ob",
    pll = FALSE,
    plotype = "lplot",
    supplot = -10,
    dtab = FALSE,
    plt = FALSE,
    text = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lrttest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(depa)) depa <- jmvcore::resolveQuo(jmvcore::enquo(depa))
    if ( ! missing(depb)) depb <- jmvcore::resolveQuo(jmvcore::enquo(depb))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(depa), depa, NULL),
            `if`( ! missing(depb), depb, NULL))


    options <- lrttestOptions$new(
        depa = depa,
        depb = depb,
        nul = nul,
        alt = alt,
        lint = lint,
        correction = correction,
        pll = pll,
        plotype = plotype,
        supplot = supplot,
        dtab = dtab,
        plt = plt,
        text = text)

    analysis <- lrttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

