
# This file is automatically generated, you probably don't want to edit this

lsampszOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lsampszOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ttype = "is",
            MW = 0.05,
            S = 3,
            d = 1.2,
            plwm = FALSE,
            tail1 = "onet",
            alpha = 0.05,
            text = TRUE, ...) {

            super$initialize(
                package="jeva",
                name="lsampsz",
                requiresData=FALSE,
                ...)

            private$..ttype <- jmvcore::OptionList$new(
                "ttype",
                ttype,
                options=list(
                    "is",
                    "po"),
                default="is")
            private$..MW <- jmvcore::OptionNumber$new(
                "MW",
                MW,
                min=0,
                max=1,
                default=0.05)
            private$..S <- jmvcore::OptionNumber$new(
                "S",
                S,
                min=0,
                max=100,
                default=3)
            private$..d <- jmvcore::OptionNumber$new(
                "d",
                d,
                min=0.05,
                max=10,
                default=1.2)
            private$..plwm <- jmvcore::OptionBool$new(
                "plwm",
                plwm,
                default=FALSE)
            private$..tail1 <- jmvcore::OptionList$new(
                "tail1",
                tail1,
                options=list(
                    "onet",
                    "twot"),
                default="onet")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                min=0,
                max=1,
                default=0.05)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)

            self$.addOption(private$..ttype)
            self$.addOption(private$..MW)
            self$.addOption(private$..S)
            self$.addOption(private$..d)
            self$.addOption(private$..plwm)
            self$.addOption(private$..tail1)
            self$.addOption(private$..alpha)
            self$.addOption(private$..text)
        }),
    active = list(
        ttype = function() private$..ttype$value,
        MW = function() private$..MW$value,
        S = function() private$..S$value,
        d = function() private$..d$value,
        plwm = function() private$..plwm$value,
        tail1 = function() private$..tail1$value,
        alpha = function() private$..alpha$value,
        text = function() private$..text$value),
    private = list(
        ..ttype = NA,
        ..MW = NA,
        ..S = NA,
        ..d = NA,
        ..plwm = NA,
        ..tail1 = NA,
        ..alpha = NA,
        ..text = NA)
)

lsampszResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lsampszResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        tab = function() private$.items[["tab"]],
        space1 = function() private$.items[["space1"]],
        space2 = function() private$.items[["space2"]],
        plotp = function() private$.items[["plotp"]],
        plotText = function() private$.items[["plotText"]],
        exptext = function() private$.items[["exptext"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Sample Size Calculator")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="tab",
                title="Sample size",
                rows=1,
                refs=list(
                    "CahusacSS",
                    "Royall"),
                clearWith=list(
                    "ttype",
                    "MW",
                    "S",
                    "sd",
                    "d"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="MW", 
                        `title`="MW prob", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `type`="number"),
                    list(
                        `name`="N", 
                        `title`="Sample size", 
                        `type`="integer"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="space1",
                title=" "))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="space2",
                title=" "))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotp",
                title="Probability of different outcomes according to sample size",
                width=500,
                height=400,
                renderFun=".plotp",
                clearWith=list(
                    "ttype",
                    "tail1",
                    "alpha",
                    "MW",
                    "S",
                    "sd",
                    "d"),
                visible="(plwm)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotText",
                title="Figure explanation",
                visible="(plwm)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="exptext",
                title="Explanation of Evidential Approach",
                refs=list(
                    "RoyallMisL",
                    "Royall",
                    "RoyallSciEv",
                    "Book"),
                visible="(text)"))}))

lsampszBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lsampszBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "lsampsz",
                version = c(1,0,0),
                options = options,
                results = lsampszResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Sample Size Calculator
#'
#' Sample size calculation for all t-tests, specifying strength of evidence 
#' required, the probability of misleading and weak evidence, and the effect 
#' size. Shows a probability plot of types of error against sample size. 
#' 
#'
#' @examples
#' jeva::lsampsz(ttype = "is", MW = 0.05, S = 3, d = 1.2, text = FALSE)
#'
#' #
#' # SAMPLE SIZE CALCULATOR
#' #
#' # Evidential sample size estimate
#' # ---------------------------------------------------------------------------------
#' #                               MW prob       S           d           Sample size
#' # ---------------------------------------------------------------------------------
#' #   Independent samples test    0.05000000    3.000000    1.200000       42.00000
#' # ---------------------------------------------------------------------------------
#' #   Note. Divide the given sample size by 2 to get the number for each group
#' #
#'
#' @param ttype type of t-test, independent (default) or paired/one sample
#' @param MW probability of misleading + weak evidence, default = 0.05
#' @param S strength of evidence required LLR, default = 3
#' @param d Cohen's d effect size, default = 1.2
#' @param plwm \code{TRUE} or \code{FALSE} (default), show the probability
#'   plots for weak  and misleading evidence
#' @param tail1 whether one- (default) or two-tailed for beta calculations
#' @param alpha probability of Type I error, default = 0.05
#' @param text \code{TRUE} (default) or \code{FALSE}, brief explanation of
#'   evidential sample size analysis
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$space1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$space2} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plotp} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$exptext} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tab$asDF}
#'
#' \code{as.data.frame(results$tab)}
#'
#' @export
lsampsz <- function(
    ttype = "is",
    MW = 0.05,
    S = 3,
    d = 1.2,
    plwm = FALSE,
    tail1 = "onet",
    alpha = 0.05,
    text = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lsampsz requires jmvcore to be installed (restart may be required)")


    options <- lsampszOptions$new(
        ttype = ttype,
        MW = MW,
        S = S,
        d = d,
        plwm = plwm,
        tail1 = tail1,
        alpha = alpha,
        text = text)

    analysis <- lsampszClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

