
# This file is automatically generated, you probably don't want to edit this

lttestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            nul = 0,
            alt = 0,
            lint = 2,
            dtab = FALSE,
            plt = FALSE,
            pll = FALSE,
            text = TRUE, ...) {

            super$initialize(
                package="jeva",
                name="lttest",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..nul <- jmvcore::OptionNumber$new(
                "nul",
                nul,
                min=-100000000000,
                max=100000000000,
                default=0)
            private$..alt <- jmvcore::OptionNumber$new(
                "alt",
                alt,
                min=-100000000000,
                max=100000000000,
                default=0)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=10,
                default=2)
            private$..dtab <- jmvcore::OptionBool$new(
                "dtab",
                dtab,
                default=FALSE)
            private$..plt <- jmvcore::OptionBool$new(
                "plt",
                plt,
                default=FALSE)
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..nul)
            self$.addOption(private$..alt)
            self$.addOption(private$..lint)
            self$.addOption(private$..dtab)
            self$.addOption(private$..plt)
            self$.addOption(private$..pll)
            self$.addOption(private$..text)
        }),
    active = list(
        dep = function() private$..dep$value,
        nul = function() private$..nul$value,
        alt = function() private$..alt$value,
        lint = function() private$..lint$value,
        dtab = function() private$..dtab$value,
        plt = function() private$..plt$value,
        pll = function() private$..pll$value,
        text = function() private$..text$value),
    private = list(
        ..dep = NA,
        ..nul = NA,
        ..alt = NA,
        ..lint = NA,
        ..dtab = NA,
        ..plt = NA,
        ..pll = NA,
        ..text = NA)
)

lttestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lttestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lttest = function() private$.items[["lttest"]],
        lttest2 = function() private$.items[["lttest2"]],
        lttestd = function() private$.items[["lttestd"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]],
        plot = function() private$.items[["plot"]],
        plotc = function() private$.items[["plotc"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="One Sample T-Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lttest",
                title="Support",
                rows=3,
                clearWith=list(
                    "nul",
                    "alt",
                    "data"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `type`="number"),
                    list(
                        `name`="mdiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="<i>t</i>", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="<i>df</i>", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="<i>p</i>", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="lttest2",
                title="Support Interval for mean",
                rows=1,
                clearWith=list(
                    "lint",
                    "data"),
                columns=list(
                    list(
                        `name`="Mean", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="lttestd",
                title="Group Descriptives",
                visible="(dtab)",
                rows=1,
                clearWith=list(
                    "data"),
                columns=list(
                    list(
                        `name`="gp", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="N", 
                        `type`="number"),
                    list(
                        `name`="Mean", 
                        `type`="number"),
                    list(
                        `name`="Median", 
                        `type`="number"),
                    list(
                        `name`="SD", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                visible="(text)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="<i>S</i>", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="<i>LR</i>", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="`Mean with S-{lint} support interval`",
                width=400,
                height=300,
                renderFun=".plot",
                clearWith=list(
                    "data",
                    "lint"),
                visible="(plt)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood function with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                clearWith=list(
                    "data",
                    "lint",
                    "nul",
                    "alt"),
                visible="(pll)"))}))

lttestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "lttest",
                version = c(1,0,0),
                options = options,
                results = lttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE)
        }))

#' One Sample T-Test
#'
#' One sample analysis where null and alternative hypotheses can be specified.
#' Likelihood interval support level can be specified and plotted with the 
#' mean.
#' A likelihood function for the mean can be plotted.
#' 
#'
#' @examples
#' data('ToothGrowth')
#' jeva::lttest(data = ToothGrowth, dep = len)
#'
#' #
#' # ONE SAMPLE T-TEST
#' #
#' # Support
#' # -------------------------------------------------------------------------------------------------------
#' #                     Value       Difference    SE           S             t           df    p
#' # -------------------------------------------------------------------------------------------------------
#' #   H₀ vs observed    0.000000    -18.813333    0.9875223    -59.019937    19.05105    59    < .0000001
#' #   Ha vs observed    0.000000    -18.813333    0.9875223    -59.019937    19.05105    59    < .0000001
#' #   Ha vs H₀                        0.000000    0.9875223      0.000000
#' # -------------------------------------------------------------------------------------------------------
#' #
#' #
#' # Support Interval for mean
#' # ------------------------------------
#' #   Mean        Lower       Upper
#' # ------------------------------------
#' #   18.81333    16.82172    20.80495
#' # ------------------------------------
#' #
#'
#' @param data the data as a data frame
#' @param dep a (non-empty) numeric vector of data values
#' @param nul value for the null hypothesis, default = 0
#' @param alt value for an alternative hypothesis, default = 0
#' @param lint likelihood interval given as support values, e.g. 2 or 3,
#'   default = 2
#' @param dtab \code{TRUE} or \code{FALSE} (default), provide descriptive
#'   statistics
#' @param plt \code{TRUE} or \code{FALSE} (default), give a plot of means with
#'   specified support intervals
#' @param pll \code{TRUE} or \code{FALSE} (default), give the likelihood
#'   function showing null hypothesis (black line),  alternative hypothesis
#'   (blue line), mean (dashed line), and specified support interval
#'   (horizontal red line)
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lttest2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$lttestd} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lttest$asDF}
#'
#' \code{as.data.frame(results$lttest)}
#'
#' @export
lttest <- function(
    data,
    dep,
    nul = 0,
    alt = 0,
    lint = 2,
    dtab = FALSE,
    plt = FALSE,
    pll = FALSE,
    text = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lttest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- lttestOptions$new(
        dep = dep,
        nul = nul,
        alt = alt,
        lint = lint,
        dtab = dtab,
        plt = plt,
        pll = pll,
        text = text)

    analysis <- lttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

