
# This file is automatically generated, you probably don't want to edit this

mcnemOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcnemOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rows = NULL,
            cols = NULL,
            counts = NULL,
            nul = 1,
            alt = 1,
            lint = 2,
            ciWidth = 95,
            correction = "ob",
            pll = FALSE,
            plotype = "lplot",
            supplot = -10,
            obs = TRUE,
            exp = FALSE,
            pcRow = FALSE,
            pcCol = FALSE,
            pcTot = FALSE,
            varA = FALSE,
            text = TRUE,
            barplot = FALSE,
            yaxis = "ycounts",
            yaxisPc = "total_pc",
            xaxis = "xrows",
            bartype = "dodge", ...) {

            super$initialize(
                package="jeva",
                name="mcnem",
                requiresData=TRUE,
                ...)

            private$..rows <- jmvcore::OptionVariable$new(
                "rows",
                rows,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cols <- jmvcore::OptionVariable$new(
                "cols",
                cols,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..nul <- jmvcore::OptionNumber$new(
                "nul",
                nul,
                min=0,
                max=100000000000,
                default=1)
            private$..alt <- jmvcore::OptionNumber$new(
                "alt",
                alt,
                min=0,
                max=100000000000,
                default=1)
            private$..lint <- jmvcore::OptionNumber$new(
                "lint",
                lint,
                min=1,
                max=100,
                default=2)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..correction <- jmvcore::OptionList$new(
                "correction",
                correction,
                options=list(
                    "nc",
                    "ob",
                    "aic"),
                default="ob")
            private$..pll <- jmvcore::OptionBool$new(
                "pll",
                pll,
                default=FALSE)
            private$..plotype <- jmvcore::OptionList$new(
                "plotype",
                plotype,
                options=list(
                    "lplot",
                    "logplot"),
                default="lplot")
            private$..supplot <- jmvcore::OptionNumber$new(
                "supplot",
                supplot,
                min=-100,
                max=-1,
                default=-10)
            private$..obs <- jmvcore::OptionBool$new(
                "obs",
                obs,
                default=TRUE)
            private$..exp <- jmvcore::OptionBool$new(
                "exp",
                exp,
                default=FALSE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=FALSE)
            private$..pcTot <- jmvcore::OptionBool$new(
                "pcTot",
                pcTot,
                default=FALSE)
            private$..varA <- jmvcore::OptionBool$new(
                "varA",
                varA,
                default=FALSE)
            private$..text <- jmvcore::OptionBool$new(
                "text",
                text,
                default=TRUE)
            private$..barplot <- jmvcore::OptionBool$new(
                "barplot",
                barplot,
                default=FALSE)
            private$..yaxis <- jmvcore::OptionList$new(
                "yaxis",
                yaxis,
                options=list(
                    "ycounts",
                    "ypc"),
                default="ycounts")
            private$..yaxisPc <- jmvcore::OptionList$new(
                "yaxisPc",
                yaxisPc,
                options=list(
                    "total_pc",
                    "column_pc",
                    "row_pc"),
                default="total_pc")
            private$..xaxis <- jmvcore::OptionList$new(
                "xaxis",
                xaxis,
                options=list(
                    "xrows",
                    "xcols"),
                default="xrows")
            private$..bartype <- jmvcore::OptionList$new(
                "bartype",
                bartype,
                options=list(
                    "dodge",
                    "stack"),
                default="dodge")

            self$.addOption(private$..rows)
            self$.addOption(private$..cols)
            self$.addOption(private$..counts)
            self$.addOption(private$..nul)
            self$.addOption(private$..alt)
            self$.addOption(private$..lint)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..correction)
            self$.addOption(private$..pll)
            self$.addOption(private$..plotype)
            self$.addOption(private$..supplot)
            self$.addOption(private$..obs)
            self$.addOption(private$..exp)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..pcTot)
            self$.addOption(private$..varA)
            self$.addOption(private$..text)
            self$.addOption(private$..barplot)
            self$.addOption(private$..yaxis)
            self$.addOption(private$..yaxisPc)
            self$.addOption(private$..xaxis)
            self$.addOption(private$..bartype)
        }),
    active = list(
        rows = function() private$..rows$value,
        cols = function() private$..cols$value,
        counts = function() private$..counts$value,
        nul = function() private$..nul$value,
        alt = function() private$..alt$value,
        lint = function() private$..lint$value,
        ciWidth = function() private$..ciWidth$value,
        correction = function() private$..correction$value,
        pll = function() private$..pll$value,
        plotype = function() private$..plotype$value,
        supplot = function() private$..supplot$value,
        obs = function() private$..obs$value,
        exp = function() private$..exp$value,
        pcRow = function() private$..pcRow$value,
        pcCol = function() private$..pcCol$value,
        pcTot = function() private$..pcTot$value,
        varA = function() private$..varA$value,
        text = function() private$..text$value,
        barplot = function() private$..barplot$value,
        yaxis = function() private$..yaxis$value,
        yaxisPc = function() private$..yaxisPc$value,
        xaxis = function() private$..xaxis$value,
        bartype = function() private$..bartype$value),
    private = list(
        ..rows = NA,
        ..cols = NA,
        ..counts = NA,
        ..nul = NA,
        ..alt = NA,
        ..lint = NA,
        ..ciWidth = NA,
        ..correction = NA,
        ..pll = NA,
        ..plotype = NA,
        ..supplot = NA,
        ..obs = NA,
        ..exp = NA,
        ..pcRow = NA,
        ..pcCol = NA,
        ..pcTot = NA,
        ..varA = NA,
        ..text = NA,
        ..barplot = NA,
        ..yaxis = NA,
        ..yaxisPc = NA,
        ..xaxis = NA,
        ..bartype = NA)
)

mcnemResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcnemResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]],
        text = function() private$.items[["text"]],
        ctt = function() private$.items[["ctt"]],
        ctt2 = function() private$.items[["ctt2"]],
        tabText = function() private$.items[["tabText"]],
        SupportTab = function() private$.items[["SupportTab"]],
        MoretabText = function() private$.items[["MoretabText"]],
        ctt3 = function() private$.items[["ctt3"]],
        plotc = function() private$.items[["plotc"]],
        barplot = function() private$.items[["barplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Paired Samples - McNemar Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="freqs",
                title="Contingency Table",
                columns=list(),
                clearWith=list(
                    "rows",
                    "cols",
                    "counts")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Log likelihood ratio analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt",
                title="Support",
                refs=list(
                    "Glover_Tut",
                    "Edwards_OR"),
                rows=3,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "nul",
                    "alt",
                    "correction"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Value", 
                        `title`="Odds Value", 
                        `type`="number"),
                    list(
                        `name`="ordiff", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="S", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="Param", 
                        `title`="Param", 
                        `type`="number"),
                    list(
                        `name`="G", 
                        `title`="G", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt2",
                title="Intervals",
                rows=3,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "lint",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="Interval", 
                        `title`="Type of interval", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `type`="text"),
                    list(
                        `name`="Odds", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number", 
                        `refs`=list(
                            "Pritikin")))))
            self$add(jmvcore::Html$new(
                options=options,
                name="tabText",
                title="Summarizing an evidential analysis",
                visible="(text)",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "correction")))
            self$add(jmvcore::Table$new(
                options=options,
                name="SupportTab",
                title="Interpreting Support S (log LR)",
                rows=7,
                visible="(text)",
                columns=list(
                    list(
                        `name`="SS", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="LR", 
                        `title`="LR", 
                        `type`="number"),
                    list(
                        `name`="Interp", 
                        `title`="Interpretation Comparing Hypotheses", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="MoretabText",
                title="More details about summaries",
                visible="(text)",
                refs=list(
                    "Book")))
            self$add(jmvcore::Table$new(
                options=options,
                name="ctt3",
                title="Variance analyses for Odds and Cross tabulation (Odds Ratio)",
                visible="(varA)",
                rows=4,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="Sv", 
                        `title`="S", 
                        `type`="number"),
                    list(
                        `name`="X2", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="dfv", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pv", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pv1", 
                        `title`="1 - p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `refs`=list(
                            "EdwardsVA")))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotc",
                title="`Likelihood curve for Odds with S-{lint} support interval`",
                width=500,
                height=400,
                renderFun=".plotc",
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "data",
                    "lint",
                    "nul",
                    "alt",
                    "plotype",
                    "supplot"),
                visible="(pll)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="barplot",
                title="Plots",
                width=450,
                height=400,
                renderFun=".barPlot",
                visible="(barplot)",
                requiresData=TRUE,
                clearWith=list(
                    "rows",
                    "cols",
                    "counts",
                    "barplot",
                    "yaxis",
                    "yaxisPc",
                    "xaxis",
                    "bartype",
                    "pcTot",
                    "pcCol",
                    "pcRow")))}))

mcnemBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mcnemBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jeva",
                name = "mcnem",
                version = c(1,0,0),
                options = options,
                results = mcnemResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Paired Samples
#'
#' Paired samples analysis (McNemar test) where null and alternative odds can 
#' be specified.
#' 
#'
#' @examples
#' dat <- data.frame(
#' First = c('Approve', 'Approve', 'Disapprove', 'Disapprove'),
#' Second = c('Approve', 'Disapprove', 'Approve', 'Disapprove'),
#' Counts = c(794, 150, 86, 570))
#'
#' jeva::mcnem(formula = Counts ~ First:Second, data = dat, text=FALSE)
#'
#'   #
#'   # PAIRED SAMPLES - MCNEMAR TEST
#'   #
#'   # Contingency Tables
#'   # ------------------------------------------------
#'   #   First         Approve    Disapprove    Total
#'   # ------------------------------------------------
#'   #   Approve           794           150      944
#'   #   Disapprove         86           570      656
#'   #   Total             880           720     1600
#'   # ------------------------------------------------
#'   #
#'   #
#'   # Support
#'   # ----------------------------------------------------------------------------------------------------------
#'   #                          Odds Value    Difference    S             Param    G            df    p
#'   # ----------------------------------------------------------------------------------------------------------
#'   #   H₀ vs observed Odds      1.000000     0.4266667    -8.2875901     1, 2    16.575180     1    0.0000468
#'   #   Ha vs observed Odds      1.000000     0.4266667    -8.7875901     2, 2    17.575180     1    0.0000276
#'   #   Ha vs H₀                              0.0000000    -0.5000000     2, 1     1.000000     1    0.3173105
#'   # ----------------------------------------------------------------------------------------------------------
#'   #   Note. S uses Occam's Bonus correction for parameters (Param).
#'   #
#'   #
#'   # Intervals
#'   # -------------------------------------------------------------------------------------
#'   #   Type of interval                  Level    Statistic     Lower         Upper
#'   # -------------------------------------------------------------------------------------
#'   #   Support for Odds                  2         0.5733333     0.4358143     0.7492639
#'   #   Likelihood-based for Odds    a    95\%       0.5733333     0.4382493     0.7452969
#'   #   Likelihood-based for Logodds      95\%      -0.5562880    -0.8249674    -0.2939726
#'   # -------------------------------------------------------------------------------------
#'   #   a See reference Pritikin et al (2017) likelihood-based intervals are more
#'   #   accurate and are parameterization-invariant compared to conventional confidence
#'   #   intervals
#'   #
#'
#' @param data the data as a data frame
#' @param rows the variable to use as the rows in the contingency table
#' @param cols the variable to use as the columns in the contingency table
#' @param counts the variable to use as the counts in the contingency table
#'   (not necessary when providing a formula, see the examples)
#' @param nul value for the null hypothesis, default = 1
#' @param alt value for the alternative hypothesis, default = 1
#' @param lint likelihood interval given as support value, e.g. 2 or 3,
#'   default = 2
#' @param ciWidth a number between 50 and 99.9 (default: 95), width of the
#'   confidence intervals to provide
#' @param correction correction for parameters, none, Occam's bonus (default)
#'   or AIC
#' @param pll \code{TRUE} or \code{FALSE} (default), give the likelihood
#'   function showing null hypothesis (black line),  alternative hypothesis
#'   (blue line), mean (dashed line), and specified support interval
#'   (horizontal red line)
#' @param plotype choose type of plot, likelihood function (default), support
#'   function
#' @param supplot To set the minimum likelihood display value in plot, in log
#'   units (default = -10)  affects the x-axis range
#' @param obs \code{TRUE} or \code{FALSE} (default), provide the observed
#'   counts
#' @param exp \code{TRUE} or \code{FALSE} (default), provide the expected
#'   counts
#' @param pcRow \code{TRUE} or \code{FALSE} (default), provide row percentages
#' @param pcCol \code{TRUE} or \code{FALSE} (default), provide column
#'   percentages
#' @param pcTot \code{TRUE} or \code{FALSE} (default), provide total
#'   percentages
#' @param varA \code{TRUE} or \code{FALSE} (default), perform variance
#'   analysis for null and alternative hypotheses
#' @param text \code{TRUE} (default) or \code{FALSE}, how to report the
#'   results
#' @param barplot \code{TRUE} or \code{FALSE} (default), show barplots
#' @param yaxis ycounts (default) or ypc. Use respectively \code{counts} or
#'   \code{percentages} for the bar plot y-axis
#' @param yaxisPc total_pc (default), column_pc, or row_pc. Use respectively
#'   percentages \code{of total}, \code{within columns}, or \code{within rows}
#'   for the bar plot y-axis.
#' @param xaxis rows (default), or columns in bar plot X axis
#' @param bartype stack or side by side (default), barplot type
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$ctt} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ctt2} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$SupportTab} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MoretabText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ctt3} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotc} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$barplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$freqs$asDF}
#'
#' \code{as.data.frame(results$freqs)}
#'
#' @export
mcnem <- function(
    data,
    rows,
    cols,
    counts = NULL,
    nul = 1,
    alt = 1,
    lint = 2,
    ciWidth = 95,
    correction = "ob",
    pll = FALSE,
    plotype = "lplot",
    supplot = -10,
    obs = TRUE,
    exp = FALSE,
    pcRow = FALSE,
    pcCol = FALSE,
    pcTot = FALSE,
    varA = FALSE,
    text = TRUE,
    barplot = FALSE,
    yaxis = "ycounts",
    yaxisPc = "total_pc",
    xaxis = "xrows",
    bartype = "dodge",
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mcnem requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(counts))
            counts <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="lhs",
                type="vars",
                subset="1")
        if (missing(rows))
            rows <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="1")
        if (missing(cols))
            cols <- jmvcore::marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                from="rhs",
                type="vars",
                subset="2")
    }

    if ( ! missing(rows)) rows <- jmvcore::resolveQuo(jmvcore::enquo(rows))
    if ( ! missing(cols)) cols <- jmvcore::resolveQuo(jmvcore::enquo(cols))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rows), rows, NULL),
            `if`( ! missing(cols), cols, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in rows) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in cols) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mcnemOptions$new(
        rows = rows,
        cols = cols,
        counts = counts,
        nul = nul,
        alt = alt,
        lint = lint,
        ciWidth = ciWidth,
        correction = correction,
        pll = pll,
        plotype = plotype,
        supplot = supplot,
        obs = obs,
        exp = exp,
        pcRow = pcRow,
        pcCol = pcCol,
        pcTot = pcTot,
        varA = varA,
        text = text,
        barplot = barplot,
        yaxis = yaxis,
        yaxisPc = yaxisPc,
        xaxis = xaxis,
        bartype = bartype)

    analysis <- mcnemClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

